// Generated by CoffeeScript 1.7.1
'use strict';
var ANN, util;

ANN = ANN || {};

ANN.util = util = (function(ann) {
  var ajax;
  ajax = function() {
    return 'ajax call';
  };
  ajax.endpoint = function(url) {
    var req;
    req = $.ajax({
      url: url
    });
    req.done(function(e) {
      return e;
    });
    return url;
  };
  ajax.setup = function(arg) {
    var setup, url, _ref;
    url = arg.url || '';
    setup = (function() {
      return $.ajaxSetup = {
        url: url
      };
    })();
    return (_ref = arg.url) != null ? _ref : arg;
  };
  return {
    ajax: ajax,
    endpoint: ajax.endpoint,
    setup: ajax.setup
  };
})(ANN || {});
